name: Deploy to Cloud Run

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDSDK_CORE_DISABLE_PROMPTS: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud (WIF)
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/556400187545/locations/global/workloadIdentityPools/github-pool/providers/github-oidc
          service_account: github-cicd@yokweb-billing-001.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Show gcloud account/config
        run: |
          set -x
          gcloud --version
          gcloud auth list
          gcloud config list
          gcloud projects describe yokweb-billing-001 --format="yaml(projectId,projectNumber)"

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-docker.pkg.dev --quiet

      - name: Build & push image with Cloud Build
        run: |
          set -x
          IMAGE="europe-docker.pkg.dev/yokweb-billing-001/webhooks-repo/stripe-webhooks-mailer:${GITHUB_SHA}"
          echo "Using image: $IMAGE"
          gcloud builds submit \
            --project yokweb-billing-001 \
            --tag "$IMAGE" \
            --verbosity=debug

      - name: Deploy to Cloud Run
        run: |
          set -x
          IMAGE="europe-docker.pkg.dev/yokweb-billing-001/webhooks-repo/stripe-webhooks-mailer:${GITHUB_SHA}"
          gcloud run deploy stripe-webhooks-mailer \
            --project yokweb-billing-001 \
            --region europe-west1 \
            --image "$IMAGE" \
            --service-account stripe-webhooks-mailer-sa@yokweb-billing-001.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --memory 512Mi --cpu 1 --concurrency 50 --timeout 30 \
            --set-env-vars BRAND_DEFAULT=trueweb,NODE_ENV=production,TEST_TO=pawel-czarnowski@wp.pl \
            --set-secrets STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,AWS_ACCESS_KEY_ID=AWS_ACCESS_KEY_ID:latest,AWS_SECRET_ACCESS_KEY=AWS_SECRET_ACCESS_KEY:latest \
            --verbosity=debug
